/**
 * @fileoverview Analytics Routes - REST API endpoints for analytics retrieval
 * @module routes/analyticsRoutes
 * @description
 * Defines routes for retrieving analytics data generated by Apache Spark.
 * All routes are protected by JWT authentication middleware.
 * 
 * Available Endpoints:
 * - GET /api/analytics/latest/:metricType - Get latest analytics for metric
 * - GET /api/analytics - Get all analytics with filters
 * - GET /api/analytics/summary - Get analytics summary
 * - GET /api/analytics/anomalies - Get all anomalies
 * - GET /api/analytics/:id - Get analytics by ID
 * - DELETE /api/analytics/:id - Delete analytics (testing only)
 * 
 * @requires express
 * @requires middleware/auth
 * @requires controllers/analyticsController
 * @created 2025-11-16
 * @updated 2025-11-16
 */

import express from 'express';
import { protect } from '../middleware/auth.js';
import {
  getLatestAnalytics,
  getAllAnalytics,
  getAnalyticsById,
  getAnomalies,
  getAnalyticsSummary,
  deleteAnalytics
} from '../controllers/analyticsController.js';

const router = express.Router();

/**
 * @route   GET /api/analytics/latest/:metricType
 * @desc    Get latest analytics for specific metric type
 * @access  Private
 * @param   metricType - Metric type (steps, calories, sleep, etc.)
 * @query   timeRange - Optional: Time range filter (7day, 30day, 90day)
 * 
 * Returns the most recent analytics document for the specified metric.
 * Returns null if no analytics found (not an error).
 */
router.get('/latest/:metricType', protect, getLatestAnalytics);

/**
 * @route   GET /api/analytics/summary
 * @desc    Get analytics summary for authenticated user
 * @access  Private
 * 
 * Returns aggregated summary of all analytics:
 * - Total analytics count
 * - Breakdown by metric type
 * - Breakdown by time range
 * - Anomalies detected count
 * - Current streaks
 * - Latest update timestamp
 */
router.get('/summary', protect, getAnalyticsSummary);

/**
 * @route   GET /api/analytics/anomalies
 * @desc    Get all anomalies for authenticated user
 * @access  Private
 * @query   metricType - Optional: Filter by metric type
 * @query   severity - Optional: Filter by severity (low, medium, high)
 * @query   since - Optional: Get anomalies since date (ISO 8601)
 * @query   limit - Optional: Limit results (default: 50)
 * 
 * Returns array of analytics documents with anomalyDetected = true
 */
router.get('/anomalies', protect, getAnomalies);

/**
 * @route   GET /api/analytics/:id
 * @desc    Get analytics by specific ID
 * @access  Private
 * @param   id - Analytics document ID (MongoDB ObjectId)
 * 
 * Returns single analytics document.
 * Returns 404 if not found or user doesn't own it.
 */
router.get('/:id', protect, getAnalyticsById);

/**
 * @route   GET /api/analytics
 * @desc    Get all analytics for authenticated user
 * @access  Private
 * @query   metricType - Optional: Filter by metric type
 * @query   timeRange - Optional: Filter by time range
 * @query   anomaliesOnly - Optional: Return only anomalies (true/false)
 * @query   limit - Optional: Limit results (default: 100, max: 500)
 * @query   skip - Optional: Skip results for pagination (default: 0)
 * @query   startDate - Optional: Filter by calculatedAt >= startDate (ISO 8601)
 * @query   endDate - Optional: Filter by calculatedAt <= endDate (ISO 8601)
 * @query   sortBy - Optional: Sort field (default: calculatedAt)
 * @query   sortOrder - Optional: Sort order (asc/desc, default: desc)
 * 
 * Returns array of analytics documents with pagination metadata.
 * 
 * Example:
 * GET /api/analytics?metricType=steps&timeRange=7day&limit=50&skip=0
 */
router.get('/', protect, getAllAnalytics);

/**
 * @route   DELETE /api/analytics/:id
 * @desc    Delete analytics by ID (testing only)
 * @access  Private
 * @param   id - Analytics document ID
 * 
 * Note: In production, analytics auto-expire via TTL index.
 * This endpoint is primarily for testing and manual cleanup.
 */
router.delete('/:id', protect, deleteAnalytics);

export default router;