---
name: Qwen3 Coder 480B A35B
version: 1.1.0
schema: v1
models:
  - name: Qwen3 Coder 480B A35B
    provider: openrouter
    model: qwen/qwen3-coder
    apiKey: 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
    defaultCompletionOptions:
      contextLength: 262144
    capabilities:
      - tool_use
    roles:
      - apply
      - chat
      - edit
